[project]
name = "fletcher"
authors = ["jollywatt <jo.alex.w@gmail.com>"]
channels = ["conda-forge/label/typst_rc", "conda-forge"]
platforms = ["osx-arm64"]

[tasks]
readme = "scripts/readme.py"
compile = "scripts/compile.nu"
test = "typst-test run"
fix = "typst-test update --exact"
manual = { cmd = "typst watch --root . docs/manual.typ", cwd = "." }
install = "scripts/install.nu"
check = "scripts/check.nu"

[feature.typst-current.dependencies]
typst = {channel = "conda-forge"}

[feature.typst-rc.dependencies]
typst = {channel = "conda-forge/label/typst_rc"}

[dependencies]
typst-test = ">=0.0.0.post106+2b4e689,<0.0.1+2b4e689"
python = ">=3.12.4,<3.13"
typos = "*"
tomli = ">=2.0.1,<2.1"
lxml = ">=5.2.2,<5.3"
nushell = ">=0.95.0,<0.96"

[environments]
current = ["typst-current"]
rc = ["typst-rc"]
