[project]
name = "fletcher"
authors = ["jollywatt <jo.alex.w@gmail.com>"]
channels = ["conda-forge"]
platforms = ["osx-arm64"]

[tasks]
readme = "scripts/readme.nu"
compile = "scripts/compile.nu"
test = "typst-test run"
fix = "typst-test update --exact"
manual = "typst watch --root . docs/manual.typ"
install = "scripts/install.nu"
check = "scripts/check.nu"

[dependencies]
typst = "0.12.0"
nushell = ">=0.95.0,<0.96"
typos = "*"
